max_width = 100
tab_spaces = 4
hard_tabs = false

# Function and struct formatting
fn_params_layout = "Compressed"
struct_lit_width = 40
struct_variant_width = 35
use_field_init_shorthand = true
use_try_shorthand = true

# Linebreaks and whitespace
match_block_trailing_comma = true
reorder_imports = true
reorder_modules = true

# Imports formatting (Stable version)
#imports_granularity = "Crate"

# Enforce idiomatic spacing
use_small_heuristics = "Max"